'use client';

import { useState } from 'react';

const FAQS = [
  {
    q: 'Is NoorAI a fatwa service?',
    a: 'No. NoorAI is an educational tool only. Responses are generated by AI and are not authoritative religious rulings. Always consult a qualified Islamic scholar for personal religious decisions.',
  },
  {
    q: 'How does citation verification work?',
    a: 'After the AI composes an answer it references specific verses or hadith in a structured format. Our citation verifier parses every reference and checks it against the database. If any reference does not exist, the answer is rejected and the LLM is retried with a stricter prompt before anything is shown to you.',
  },
  {
    q: 'Why only sahih and hasan hadith?',
    a: 'Weak (daif) hadith have deficiencies in their chain of narration and are generally not used as evidence for Islamic rulings. Fabricated (mawdu) hadith are not attributable to the Prophet ﷺ at all. We store them for research purposes but they never appear in answers.',
  },
  {
    q: 'What languages are supported?',
    a: 'You can ask in English, Arabic, Urdu, French, or Turkish. Quran translations are available in all five languages. Hadith are available in English and Arabic.',
  },
  {
    q: 'Can I flag an answer if it seems wrong?',
    a: 'Yes. Every answer has a "Flag issue" button. Flagged answers are queued for review by our panel of qualified Islamic scholars who can approve, correct, or annotate them.',
  },
  {
    q: 'Is my data private?',
    a: 'Your questions are not sold to third parties. Sessions are authenticated with signed JWTs and all traffic is encrypted over HTTPS. You can use NoorAI without creating an account for basic questions.',
  },
  {
    q: 'Which AI model powers the answers?',
    a: 'NoorAI uses Anthropic\'s Claude (claude-sonnet-4-6 by default) with a strict system prompt that restricts it to only the context retrieved from our database. The model cannot access the internet or invent references.',
  },
];

function FAQItem({ q, a }: { q: string; a: string }) {
  const [open, setOpen] = useState(false);
  return (
    <div className="border-b border-sage-100 last:border-0">
      <button
        onClick={() => setOpen(v => !v)}
        className="w-full flex items-center justify-between py-5 text-left gap-4 group"
      >
        <span className="text-base font-medium text-sage-900 group-hover:text-sage-700 transition-colors">
          {q}
        </span>
        <span className={`shrink-0 w-6 h-6 rounded-full border border-sage-200 flex items-center
                          justify-center text-sage-400 transition-transform duration-200
                          ${open ? 'rotate-180 bg-sage-50' : ''}`}>
          <svg width="12" height="12" viewBox="0 0 12 12" fill="currentColor">
            <path d="M2 4l4 4 4-4" stroke="currentColor" strokeWidth="1.5" fill="none"
              strokeLinecap="round" strokeLinejoin="round"/>
          </svg>
        </span>
      </button>
      {open && (
        <div className="pb-5 text-sm text-sage-500 leading-relaxed animate-fade-in pr-10">
          {a}
        </div>
      )}
    </div>
  );
}

export function FAQSection() {
  return (
    <section id="faq" className="py-24 bg-cream-100">
      <div className="max-w-3xl mx-auto px-5">
        <div className="text-center mb-14">
          <span className="inline-block text-xs font-semibold text-sage-500 uppercase tracking-widest
                           bg-white border border-sage-200 px-4 py-1.5 rounded-full mb-4">
            FAQ
          </span>
          <h2 className="text-4xl font-bold text-sage-950 tracking-tight">
            Common questions
          </h2>
        </div>

        <div className="bg-white rounded-2xl border border-sage-100 shadow-card px-6 divide-y divide-sage-100">
          {FAQS.map(item => <FAQItem key={item.q} {...item} />)}
        </div>
      </div>
    </section>
  );
}
