export default function AboutPage() {
  return (
    <div className="max-w-2xl mx-auto space-y-8">
      <h1 className="text-3xl font-bold text-green-900">About NoorAI</h1>

      <section className="bg-white rounded-2xl p-6 shadow-sm border border-stone-200 space-y-4">
        <h2 className="text-xl font-semibold text-green-800">Our Sources</h2>
        <p className="text-stone-600 leading-relaxed">
          NoorAI answers questions exclusively from two primary sources:
          the <strong>Holy Quran</strong> and <strong>authentic (sahih/hasan) Hadith</strong>.
          We never reference weak (daif) or fabricated (mawdu) narrations in AI responses.
        </p>

        <h3 className="font-semibold text-stone-700 mt-4">Hadith Collections Used</h3>
        <ul className="list-disc list-inside space-y-1 text-stone-600 text-sm">
          <li>Sahih al-Bukhari</li>
          <li>Sahih Muslim</li>
          <li>Sunan Abu Dawud</li>
          <li>Jami al-Tirmidhi</li>
          <li>Sunan al-Nasai</li>
          <li>Sunan Ibn Majah</li>
          <li>Muwatta Imam Malik</li>
          <li>Musnad Ahmad ibn Hanbal</li>
        </ul>

        <h3 className="font-semibold text-stone-700 mt-4">Grading Methodology</h3>
        <p className="text-stone-600 text-sm leading-relaxed">
          Only hadith classified as <strong>Sahih (authentic)</strong> or{' '}
          <strong>Hasan (good)</strong> by classical Hadith scholars are used in answer
          generation. All citations are verified against our database — the AI cannot
          fabricate a reference.
        </p>
      </section>

      <section className="bg-amber-50 border border-amber-200 rounded-2xl p-6 space-y-3">
        <h2 className="text-lg font-semibold text-amber-800">Important Disclaimer</h2>
        <p className="text-amber-700 text-sm leading-relaxed">
          NoorAI is an educational tool only. Responses are generated by AI and are{' '}
          <strong>not fatwas</strong> or authoritative religious rulings. Always consult
          a qualified Islamic scholar for personal religious decisions.
        </p>
        <p className="text-amber-700 text-sm">
          Every answer carries an AI disclaimer and a flagging option so the community
          and our scholar advisors can review and correct any errors.
        </p>
      </section>

      <section className="bg-white rounded-2xl p-6 shadow-sm border border-stone-200">
        <h2 className="text-lg font-semibold text-green-800 mb-3">Scholar Advisory</h2>
        <p className="text-stone-600 text-sm leading-relaxed">
          NoorAI maintains a panel of qualified Islamic scholars who review flagged answers,
          approve verified responses, and audit a random sample of AI answers quarterly.
          Scholar-verified answers are marked with a badge.
        </p>
      </section>
    </div>
  );
}
